### ISSUE TITLE
Allow a single source substitution to feed multiple destinations

### ISSUE THREAD

**Issue by darrendejaeger** [att-comdev/deckhand#21]
Current substitution looks similar to this:

```
  substitutions:
    - src:
        schema: pegleg/CommonSoftwareConfig/v1
        name: common-software-config
        path: .osh.region_name
      dest:
        path: .osh.keystone.admin.region_name
    - src:
        schema: pegleg/CommonSoftwareConfig/v1
        name: common-software-config
        path: .osh.region_name
      dest:
        path: .osh.cinder.cinder.region_name
...
```

It would be great if we could do something like this:

```
  substitutions:
    - src:
        schema: pegleg/CommonSoftwareConfig/v1
        name: common-software-config
        path: .osh.region_name
      dests:
        - path: .osh.keystone.admin.region_name
        - path: .osh.cinder.cinder.region_name
...
```
